## name:     Gruvbox Light
## license:  MIT
## upstream: https://github.com/gruvbox-community/gruvbox-contrib/blob/master/kitty/gruvbox-light.conf
## blurb:    Retro groove color scheme, light variant.

# The basic colors
foreground              #3c3836
background              #fbf1c7
selection_foreground    #fbf1c7
selection_background    #665c54

# Cursor colors
cursor                  #665c54
cursor_text_color       #bdae93

# URL underline color when hovering with mouse
url_color               #458588

# Kitty window border colors
active_border_color     #b57614
inactive_border_color   #af9e83
bell_border_color       #d79921

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #fbf1c7
active_tab_background   #3c3836
inactive_tab_foreground #3c3836
inactive_tab_background #fbf1c7
tab_bar_background      #ebdbb2

# Colors for marks (marked text in the terminal)
mark1_foreground #fbf1c7
mark1_background #b57614
mark2_foreground #fbf1c7
mark2_background #8f3f71
mark3_foreground #fbf1c7
mark3_background #076678

# The 16 terminal colors

# black
color0 #ebdbb2
color8 #928374

# red
color1  #cc241d
color9  #9d0006

# green
color2  #98971a
color10 #79740e

# yellow
color3  #d79921
color11 #b57614

# blue
color4  #458588
color12 #076678

# magenta
color5  #b16286
color13 #8f3f71

# cyan
color6  #689d6a
color14 #427b58

# white
color7  #7c6f64
color15 #282828
