name = "gruvbox-dark"

[apps]
gtk_theme = "Gruvbox-Dark"
color_scheme = "prefer-dark"
icon_theme = "Papirus-Dark"
icon_accent = "orange"
kitty_theme = "gruvbox-dark"
lsd_theme = "gruvbox-dark"
nvim_theme = "gruvbox-dark"
swaync_theme = "gruvbox-dark"
rofi_theme = "gruvbox-dark"
waybar_theme = "gruvbox-dark"
herdr_theme = "gruvbox-dark"
claude_theme = "gruvbox-dark"
yazi_theme = "gruvbox-dark"

[palette]
base = "dark"
bg = "#282828"
fg = "#ebdbb2"
accent = "#d79921"
muted = "#7c6f64"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
purple = "#d3869b"
cyan = "#8ec07c"
orange = "#fe8019"
selection_bg = "#504945"
