# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#8ec07c" }

# Find
find_keyword  = { fg = "#fabd2f", bold = true, italic = true, underline = true }
find_position = { fg = "#d3869b", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }
marker_marked   = { fg = "#8ec07c", bg = "#8ec07c" }
marker_selected = { fg = "#fabd2f", bg = "#fabd2f" }

# Count
count_copied   = { fg = "#282828", bg = "#b8bb26" }
count_cut      = { fg = "#282828", bg = "#fb4934" }
count_selected = { fg = "#282828", bg = "#fabd2f" }

# Border
border_symbol = "│"
border_style  = { fg = "#928374" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#282828", bg = "#d79921", bold = true }
inactive = { fg = "#d79921", bg = "#3c3836" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#282828", bg = "#d79921", bold = true }
normal_alt  = { fg = "#d79921", bg = "#3c3836" }

# Select mode
select_main = { fg = "#282828", bg = "#8ec07c", bold = true }
select_alt  = { fg = "#8ec07c", bg = "#3c3836" }

# Unset mode
unset_main = { fg = "#282828", bg = "#fe8019", bold = true }
unset_alt  = { fg = "#fe8019", bg = "#3c3836" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#928374" }
perm_type  = { fg = "#d79921" }
perm_read  = { fg = "#fabd2f" }
perm_write = { fg = "#fb4934" }
perm_exec  = { fg = "#b8bb26" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#b8bb26", bg = "#504945" }
progress_error  = { fg = "#fabd2f", bg = "#fb4934" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#d79921" }
active   = { fg = "#d3869b", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#d79921" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#d79921" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#d79921" }
title   = {}
hovered = { fg = "#d3869b", bold = true }

# : }}}


# : Which {{{

[which]
border          = { fg = "#d79921" }
cand            = { fg = "#8ec07c" }
rest            = { fg = "#7c6f64" }
desc            = { fg = "#d3869b" }
separator       = "  "
separator_style = { fg = "#665c54" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#8ec07c" }
run     = { fg = "#d3869b" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#3c3836", bg = "#ebdbb2" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#d79921" }
title    = { fg = "#d79921" }
tbl_col  = { fg = "#8ec07c" }
tbl_cell = { fg = "#d3869b", bg = "#504945" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#b8bb26" }
title_warn  = { fg = "#fabd2f" }
title_error = { fg = "#fb4934" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "**/image/*", fg = "#8ec07c" },
	# Media
	{ mime = "**/{audio,video}/*", fg = "#fabd2f" },
	# Archive
	{ mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#d3869b" },
	# Document
	{ mime = "**/application/{pdf,doc,rtf}", fg = "#b8bb26" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#7c6f64" },
	# Fallback
	{ url = "*", fg = "#ebdbb2" },
	{ url = "*/", fg = "#d79921" },
]

# : }}}

[icon]

dirs = [
	{ name = ".config", text = "", fg = "#d3869b" },
	{ name = ".git", text = "", fg = "#8ec07c" },
	{ name = ".github", text = "", fg = "#d79921" },
	{ name = ".npm", text = "", fg = "#d79921" },
	{ name = "Desktop", text = "", fg = "#8ec07c" },
	{ name = "Development", text = "", fg = "#8ec07c" },
	{ name = "Documents", text = "", fg = "#8ec07c" },
	{ name = "Downloads", text = "", fg = "#8ec07c" },
	{ name = "Library", text = "", fg = "#8ec07c" },
	{ name = "Movies", text = "", fg = "#8ec07c" },
	{ name = "Music", text = "", fg = "#8ec07c" },
	{ name = "Pictures", text = "", fg = "#8ec07c" },
	{ name = "Public", text = "", fg = "#8ec07c" },
	{ name = "Videos", text = "", fg = "#8ec07c" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#ebdbb2" },
	{ if = "link", text = "", fg = "#928374" },
	{ if = "block", text = "", fg = "#fe8019" },
	{ if = "char", text = "", fg = "#fe8019" },
	{ if = "fifo", text = "", fg = "#fe8019" },
	{ if = "sock", text = "", fg = "#fe8019" },
	{ if = "sticky", text = "", fg = "#fe8019" },
	{ if = "dummy", text = "", fg = "#fb4934" },

	# Fallback
	{ if = "dir & hovered", text = "", fg = "#d79921" },
	{ if = "dir", text = "", fg = "#d79921" },
	{ if = "exec", text = "", fg = "#b8bb26" },
	{ if = "!dir", text = "", fg = "#ebdbb2" },
]
