name = "catppuccin-macchiato-mauve"

[apps]
gtk_theme = "catppuccin-macchiato-mauve-standard+default"
color_scheme = "prefer-dark"
icon_theme = "Papirus-Dark"
icon_accent = "cat-macchiato-mauve"
kitty_theme = "catppuccin-macchiato-mauve"
lsd_theme = "catppuccin-macchiato-mauve"
nvim_theme = "catppuccin-macchiato-mauve"
swaync_theme = "catppuccin-macchiato-mauve"
rofi_theme = "catppuccin-macchiato-mauve"
waybar_theme = "catppuccin-macchiato-mauve"
herdr_theme = "catppuccin-macchiato-mauve"
claude_theme = "catppuccin-macchiato-mauve"
yazi_theme = "catppuccin-macchiato"

[palette]
base = "dark"
bg = "#24273a"
fg = "#cad3f5"
accent = "#c6a0f6"
muted = "#6e738d"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
purple = "#c6a0f6"
cyan = "#8bd5ca"
orange = "#f5a97f"
selection_bg = "#494d64"
