name = "catppuccin-latte"

[apps]
color_scheme = "prefer-light"
icon_theme = "Papirus-Light"
icon_accent = "cat-latte-mauve"
gtk_theme = "catppuccin-latte-mauve-standard+default"
kitty_theme = "catppuccin-latte"
waybar_theme = "catppuccin-latte"
rofi_theme = "catppuccin-latte"
swaync_theme = "catppuccin-latte"
lsd_theme = "catppuccin-latte"
nvim_theme = "catppuccin-latte"
herdr_theme = "catppuccin-latte"
claude_theme = "catppuccin-latte"
yazi_theme = "catppuccin-latte"

[palette]
base = "light"
bg = "#eff1f5"
fg = "#4c4f69"
accent = "#8839ef"
muted = "#6c6f85"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
purple = "#8839ef"
cyan = "#179299"
orange = "#fe640b"
selection_bg = "#ccd0da"
